#!/usr/bin/env python3
from pathlib import Path
import shutil, time
root=Path.cwd(); p=root/'lib/sync/p2p_sync.dart'
if not p.exists(): raise SystemExit(f'MISSING: {p}')
backup=root/f'.brain2_bootstrap_wirehash_backup_{int(time.time())}'; backup.mkdir()
dst=backup/p.relative_to(root); dst.parent.mkdir(parents=True,exist_ok=True); shutil.copy2(p,dst)
s=p.read_text()
if '_bootstrapWireHashMaterial' not in s:
    anchor='''const int _brain2TransportMaxReassembledBytes = 64 * 1024 * 1024;\n'''
    insert=anchor+'''\nString _bootstrapWireHashMaterial(\n  String memoryRoot,\n  String table,\n  int ordinal,\n  String recordsJson,\n) =>\n    'B2BOOTSTRAP3\\u0000$memoryRoot\\u0000$table\\u0000$ordinal\\u0000$recordsJson';\n\nString _hashBootstrapWireChunk(\n  String memoryRoot,\n  String table,\n  int ordinal,\n  String recordsJson,\n) =>\n    sha256Hex(_bootstrapWireHashMaterial(memoryRoot, table, ordinal, recordsJson));\n'''
    if anchor not in s: raise SystemExit('mobile constant anchor not found')
    s=s.replace(anchor,insert,1)
old='''      case 'bootstrap_chunk':\n        final memoryRoot = '${message['memoryRoot']}';\n        final wireTable = '${message['table']}';\n        final ordinal = message['ordinal'] is num\n            ? (message['ordinal'] as num).toInt()\n            : int.parse('${message['ordinal']}');\n        final records = (message['records'] as List)\n            .map((e) => (e as Map).cast<String, Object?>())\n            .toList(growable: false);\n        final expected = '${message['chunkHash']}';\n        final actual = sha256Hex(\n          canonicalJson({\n            'memoryRoot': memoryRoot,\n            'table': wireTable,\n            'ordinal': ordinal,\n            'records': records,\n          }),\n        );\n        if (actual != expected) {\n          throw StateError('Brain2 bootstrap chunk hash mismatch');\n        }'''
new='''      case 'bootstrap_chunk':\n        final memoryRoot = '${message['memoryRoot']}';\n        final wireTable = '${message['table']}';\n        final ordinal = message['ordinal'] is num\n            ? (message['ordinal'] as num).toInt()\n            : int.parse('${message['ordinal']}');\n        final expected = '${message['chunkHash']}';\n\n        late final List<Map<String, Object?>> records;\n        late final String actual;\n        if (message['hashVersion'] == 3 && message['recordsJson'] is String) {\n          final recordsJson = message['recordsJson'] as String;\n          actual = _hashBootstrapWireChunk(\n            memoryRoot,\n            wireTable,\n            ordinal,\n            recordsJson,\n          );\n          final decoded = jsonDecode(recordsJson);\n          if (decoded is! List) {\n            throw StateError('Brain2 bootstrap recordsJson is not a list');\n          }\n          records = decoded\n              .map((e) => (e as Map).cast<String, Object?>())\n              .toList(growable: false);\n        } else {\n          records = (message['records'] as List)\n              .map((e) => (e as Map).cast<String, Object?>())\n              .toList(growable: false);\n          actual = sha256Hex(\n            canonicalJson({\n              'memoryRoot': memoryRoot,\n              'table': wireTable,\n              'ordinal': ordinal,\n              'records': records,\n            }),\n          );\n        }\n        if (actual != expected) {\n          throw StateError('Brain2 bootstrap chunk hash mismatch');\n        }'''
if old in s: s=s.replace(old,new,1)
elif "message['hashVersion'] == 3" not in s: raise SystemExit('mobile receiver anchor not found')
old='''          final hash = sha256Hex(\n            canonicalJson({\n              'memoryRoot': root,\n              'table': wireTable,\n              'ordinal': ordinal,\n              'records': current,\n            }),\n          );\n          await _send(peer, {\n            'type': 'bootstrap_chunk',\n            'memoryRoot': root,\n            'table': wireTable,\n            'records': current,\n            'ordinal': ordinal,\n            'chunkHash': hash,\n          });'''
new='''          // Serialize once and hash the exact JSON text that crosses the wire.\n          // This avoids Dart↔JavaScript canonicalization differences.\n          final recordsJson = jsonEncode(current);\n          final hash = _hashBootstrapWireChunk(\n            root,\n            wireTable,\n            ordinal,\n            recordsJson,\n          );\n          await _send(peer, {\n            'type': 'bootstrap_chunk',\n            'memoryRoot': root,\n            'table': wireTable,\n            'recordsJson': recordsJson,\n            'hashVersion': 3,\n            'ordinal': ordinal,\n            'chunkHash': hash,\n          });'''
if old in s: s=s.replace(old,new,1)
elif "'hashVersion': 3" not in s: raise SystemExit('mobile sender anchor not found')
p.write_text(s)
print('PASS: mobile bootstrap wire-hash v3 patch applied.')
print(f'Backup: {backup.name}')
