import '../core/identity.dart';
import 'r1_graph.dart';

const String brain2R2GraphVersion='B2_R2_GRAPH_V1';
class R2GraphNode{final String id,kind,statement,status;final String? projectId;final List<String> derivedFrom,requiredEvidence,staleWhen;final double confidence;final Map<String,Object?> metadata;const R2GraphNode({required this.id,required this.kind,required this.statement,required this.derivedFrom,required this.confidence,required this.status,this.projectId,this.requiredEvidence=const[],this.staleWhen=const[],this.metadata=const{}});Map<String,Object?>toJson()=>{'id':id,'kind':kind,'projectId':projectId,'statement':statement,'derivedFrom':derivedFrom,'confidence':confidence,'status':status,'requiredEvidence':requiredEvidence,'staleWhen':staleWhen,'metadata':metadata};}
class R2GraphEdge{final String id,from,to,type;const R2GraphEdge({required this.id,required this.from,required this.to,required this.type});Map<String,Object?>toJson()=>{'id':id,'from':from,'to':to,'type':type};}
class R2Graph{final List<R2GraphNode>nodes;final List<R2GraphEdge>edges;final String rootHash;const R2Graph({required this.nodes,required this.edges,required this.rootHash});Map<String,Object?>toJson()=>{'format':'B2_R2_GRAPH','version':1,'graphVersion':brain2R2GraphVersion,'nodes':nodes.map((e)=>e.toJson()).toList(),'edges':edges.map((e)=>e.toJson()).toList(),'rootHash':rootHash};}
R2Graph buildR2Graph(R1Graph r1,List<Map<String,Object?>> proposals){final r1Ids=r1.nodes.map((e)=>e.id).toSet();final nodes=<R2GraphNode>[];final edges=<R2GraphEdge>[];for(final p in proposals){final refs=((p['derivedFrom'] as List?)??const[]).map((e)=>'$e').toSet().toList()..sort();if(refs.isEmpty||refs.any((e)=>!r1Ids.contains(e)))throw StateError('Every R2 node must derive from existing R1 node IDs.');final statement='${p['statement']??''}';final kind='${p['kind']??'HYPOTHESIS'}';final id=canonicalId('r2n',[brain2R2GraphVersion,kind,p['projectId'],statement,...refs]);final confidence=((p['confidence'] as num?)??0).toDouble().clamp(0,1).toDouble();final required=((p['requiredEvidence'] as List?)??const[]).map((e)=>'$e').toSet().toList()..sort();final stale=((p['staleWhen'] as List?)??const[]).map((e)=>'$e').toSet().toList()..sort();final node=R2GraphNode(id:id,kind:kind,statement:statement,derivedFrom:refs,confidence:confidence,status:'${p['status']??'PROVISIONAL'}',projectId:p['projectId']?.toString(),requiredEvidence:required,staleWhen:stale,metadata:(p['metadata'] as Map?)?.map((k,v)=>MapEntry('$k',v))??const{});nodes.add(node);for(final source in refs){edges.add(R2GraphEdge(id:canonicalId('r2e',[brain2R2GraphVersion,id,'DERIVED_FROM',source]),from:id,to:source,type:'DERIVED_FROM'));}}nodes.sort((a,b)=>a.id.compareTo(b.id));final byId=<String,R2GraphEdge>{for(final e in edges)e.id:e};final sorted=byId.values.toList()..sort((a,b)=>a.id.compareTo(b.id));final rootMaterial=[nodes.map((n)=>[n.id,n.kind,n.projectId??'',n.statement,n.derivedFrom,n.confidence,n.status,n.requiredEvidence,n.staleWhen]).toList(),sorted.map((e)=>[e.id,e.from,e.to,e.type]).toList()];return R2Graph(nodes:nodes,edges:sorted,rootHash:sha256Hex(canonicalJson(rootMaterial)));}
void assertR2CannotMutateR1(R1Graph r1,R2Graph r2){for(final node in r2.nodes){if(node.derivedFrom.isEmpty)throw StateError('R2 node ${node.id} has no R1 derivation.');if(node.metadata['currentTruth']==true)throw StateError('R2 node ${node.id} attempted to self-promote to Current Truth.');}}
